export const SMPP_AUTH_RESULTS = {
  SUCCESS: "SUCCESS",
  INVALID_SYSTEM_ID: "INVALID_SYSTEM_ID",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  IP_NOT_ALLOWED: "IP_NOT_ALLOWED",
  BIND_LIMIT_REACHED: "BIND_LIMIT_REACHED",
} as const;

export type SmppAuthenticationResult =
  (typeof SMPP_AUTH_RESULTS)[keyof typeof SMPP_AUTH_RESULTS];